### ISSUE TITLE
Create index page 

### ISSUE THREAD

**Issue by JAjorgbor** [nathanieluriri/bluspan-website#1]
@nathanieluriri  I'm going to be working on making the index page if there are any issues or tasks you want to assign its best to do it through github issues then whenever I make a pull request I'll attatch an issue to it so that your know what problem i'm fixing, i'm going to make a local branch on my system, I'd advice that you make a sandbox branch so that we can commit all our immediate changes there, any approved change would be merged to the main branch which would ideally be the branch that'll be deployed

**Comment by nathanieluriri** [comment]
Understood
